Add object permissions based on django-guardian
girder/dkc-next pull request #66
Opened 2020-10-29 21:54 UTC by jbeezley

So far this only contains model layer logic on folders (files will be similar).  I will work on the rest layer next to give a better sense of how it is used.

2020-10-29 23:57 UTC, zachmullen commented on dkc/core/models/tree.py
> +            (Permission.read.value.split('.')[1], 'Read access to a tree'),
Can the names not have `.` in them?

2020-10-30 00:02 UTC, zachmullen commented on dkc/core/models/tree.py
> +        return False
I think this is more readable / expressive as

```python
return any(user.has_perm(perm, self) for perm in permission.derived_permissions)
```

Also I find the name "derived_permissions" confusing here, as reading it out of context makes it seem backwards to what you expect. It's only the derived permissions if you're talking about *required* permission, not the permission *assigned* to a user. I'm struggling to come up with a great name, but I think capturing that it only works in that direction would be prudent.

2020-10-30 00:08 UTC, zachmullen commented on dkc/core/tests/test_permissions.py
> +    assert {tree.id for tree in trees} == {admin_tree.id}
This test seems like a good case for `@pytest.mark.parametrize`, no?

2020-10-30 13:05 UTC, jbeezley commented
I'll address  minor issues later, I'm pushing this as a proof of concept for the moment.  I also have to go through and fix the folder rest tests.

One thing to note about the behavior as implemented is that you get a 404 on requests for objects that you don't have read access to, but a 403 when trying to write to an object that you only have read access.  I could see an argument for wanting a 403 in both cases.

Finally, we need to decide on a method for providing `public` access either by a column on the tree table or by a default group.  I'm leaning toward the group method because I'm not sure how to add the condition inside the `has_perm` query.

2020-10-30 13:09 UTC, zachmullen commented
> One thing to note about the behavior as implemented is that you get a 404 on requests for objects that you don't have read access to, but a 403 when trying to write to an object that you only have read access. I could see an argument for wanting a 403 in both cases.

In my experience this is actually the most common behavior, and I'd say the most desirable for security. A 404 doesn't leak information about even the existence of a resource, other than perhaps via side channels.

From a behavioral perspective, it can be really nice for clients if, when read access is denied to an anonymous user, a 401 is returned. However, that subverts the "don't-leak-information-about-resource-existence" principle.

2020-10-30 13:21 UTC, zachmullen commented
> Finally, we need to decide on a method for providing public access either by a column on the tree table or by a default group. I'm leaning toward the group method because I'm not sure how to add the condition inside the has_perm query.

A group permission check seems like it requires a JOIN of at least 3 tables. It may be worth considering an optimized path like a `public` column on the Tree, which could obviate that database query entirely. I guess the decision comes down to how difficult it is to achieve that column check in our own code.

2020-10-30 14:19 UTC, jbeezley commented
> A group permission check seems like it requires a JOIN of at least 3 tables. It may be worth considering an optimized path like a public column on the Tree, which could obviate that database query entirely.

I realized I misspoke.  We can handle `has_perm` in python.  The issue is with integrating into `get_objects_for_user`.  It returns a [filtered queryset](https://github.com/django-guardian/django-guardian/blob/devel/guardian/shortcuts.py#L648), but we would need to find a way to add a special `OR` condition inside the filter.

2020-10-30 20:51 UTC, jbeezley commented
I'm to the point now where I need to design the rest interface for permissions.  I have two different options in mind:

1. Simple, something similar to:
```
POST /folders/:id/permissions permission=read user_id=1
DELETE /folders/:id/permissions permission=read user_id=1

POST /folders/:id/permissions permission=write group_id=1
DELETE /folders/:id/permissions permission=read group_id=1

GET /folders/:id/permissions
=>
{
  read: {users: [1, 4], groups: [1]},
  write: {users: [2], groups: []},
  admin: {users: [3], groups: []}
}
```

2. Elaborate--Full CRUD subroutes on `/folders/:id/permissions/users` and `/folders/:id/permissions/groups` using drf-nested-routers.

The other complication is what to do about permissions on users and groups themselves.  If we want user information to be private, then it begs the question of what to do about user permissions on a tree that the admin of the tree doesn't have access to.  Option 1 bypasses this for the most part by only returning the id of the users.  We would need to add `/users` and `/groups` routes to look up the actual user/group information in the UI, which could be completed in a follow-up PR.

2020-11-03 19:57 UTC, jbeezley commented
I added an MVP for the permissions api.  Individual permissions are serialized like `{'id': 1, 'model': 'user', 'permission': 'read'}`.  It's a little more verbose than what I described before, but it allows the permissions to be returned as a flat list.  I'm deferring an api for user group information for a future PR.

There are all sorts of edge cases we could add handling for e.g. preventing explicit permissions for admin users, preventing duplicate permissions for a single user, adding special semantics for public permissions, etc.

2020-11-11 20:04 UTC, jbeezley commented
This is almost ready for a more detailed review.  The only major thing I might want to change is swap out id's for group/user names in the permissions API.

2020-11-19 15:22 UTC, zachmullen commented on dkc/core/rest/folder.py
> +    name = serializers.CharField(required=True)
Non-actionable comment for posterity: if we also wanted to support an ID-based API, this is forward compatible. We would just make `name` not required, and add an `id` field, and one of them would have to be set.

2020-11-19 18:21 UTC, zachmullen commented on dkc/core/models/folder.py
> +        return queryset.filter(tree__in=models.Subquery(tree_query))
Another non-actionable comment for information. This builds queries of the form:

```python
>>> q = Folder.filter_by_permission(user, Permission.read, Folder.objects)
>>> print(q.query)
SELECT "core_folder"."id", "core_folder"."created", "core_folder"."modified", "core_folder"."name", "core_folder"."depth", "core_folder"."size", "core_folder"."description", "core_folder"."user_metadata", "core_folder"."parent_id", "core_folder"."tree_id" FROM "core_folder" WHERE "core_folder"."tree_id" IN ((SELECT "core_tree"."id" FROM "core_tree") UNION (SELECT "core_tree"."id" FROM "core_tree" WHERE "core_tree"."public")) ORDER BY "core_folder"."name" ASC

>>> q = Folder.filter_by_permission(user, Permission.write, Folder.objects)
>>> print(q.query)
SELECT "core_folder"."id", "core_folder"."created", "core_folder"."modified", "core_folder"."name", "core_folder"."depth", "core_folder"."size", "core_folder"."description", "core_folder"."user_metadata", "core_folder"."parent_id", "core_folder"."tree_id" FROM "core_folder" WHERE "core_folder"."tree_id" IN (SELECT U0."id" FROM "core_tree" U0) ORDER BY "core_folder"."name" ASC
```
```

2020-11-19 19:06 UTC, zachmullen requested changes

2020-11-19 19:06 UTC, zachmullen commented on dkc/core/rest/folder.py
> +        self.remove_permission_list(tree, list(existing_grant_set - grant_set))
This explains the `frozen`-ness of `PermissionGrant`. I like the set-based approach, but does it make sense to move all this stuff (`set_permission_list`, `remove_permission_list`, `grant_permission_list`) down into the Tree model?

2020-12-10 19:24 UTC, jbeezley commented on dkc/core/permissions.py
> +    def has_object_permission(self, request: Request, view: View, obj: Folder) -> bool:
I intended to implement a duck typed API for use with this class.  The minimal set of methods required are `filter_by_permission` and `has_permission`.  See [`e46203a`](https://github.com/girder/dkc-next/pull/66/commits/e46203a06d559c2dc9660c076bebd9448cff7152) where I implement it on files.

In general, this is what I had in mind for adding ACL's to additional models, but I wanted to get some feedback on it before writing elaborate documentation.

2020-12-10 19:43 UTC, jbeezley commented on dkc/core/permissions.py
> +    def implied_permissions(self) -> List[str]:
I understand what you mean.  I think this is addressed in [`56dddf3`](https://github.com/girder/dkc-next/pull/66/commits/56dddf338e4131311d10dd138d0dccbfcee66440).

2020-12-10 19:49 UTC, zachmullen commented on dkc/core/permissions.py
> +    def associated_permissions(self) -> List[str]:
👍

2020-12-10 19:52 UTC, zachmullen approved these changes
LGTM. I'd like @brianhelba to also take a look, at least at the test code.

2020-12-17 16:06 UTC, brianhelba reviewed
Some comments so far, I'm still looking at all of it...

2021-01-14 16:11 UTC, mgrauer commented
@jbeezley Can you please update this docs as part of this PR, and add all DKCN specific assumptions to the doc that drove your design?

https://github.com/girder/dkc-next/blob/master/docs/roadmap-authorization.md

2021-01-14 17:38 UTC, jbeezley commented
I added some documentation to the model/permissions layer.  I think it addresses the motivations for the code at a high level.  The roadmap doc can go into more detail as to policy decisions.

2021-01-15 15:52 UTC, mgrauer commented
@jbeezley what review do you need of this (after resolving merge conflicts) to get this merged? Is it code or comments or both?

2021-01-15 17:21 UTC, jbeezley commented
I guess mostly the comments.

2021-01-15 21:00 UTC, mgrauer commented
@brianhelba @zachmullen could one of you review comments in this PR?

2021-01-15 22:07 UTC, zachmullen requested changes
comments reviewed

2021-01-15 22:07 UTC, zachmullen commented on dkc/core/models/tree.py
> +        This method with apply a user or group permission to the current entity.  This
with -> will

2021-01-15 22:07 UTC, zachmullen commented on dkc/core/permissions.py
> +    A list tree access permissions.
This sentence doesn't parse for me, should it be "a list of"?

2021-01-15 22:16 UTC, mgrauer requested changes

2021-01-15 22:16 UTC, mgrauer commented on dkc/core/models/tree.py
> +            # This is a special case for the anonymous user.  Acess can only
```suggestion
            # This is a special case for the anonymous user.  Access can only
```

2021-01-18 14:10 UTC, zachmullen approved these changes

2021-01-18 21:02 UTC, merged